apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-nginx-app
  template:
    metadata:
      labels:
        app: php-nginx-app
    spec:
      containers:
        - name: php-nginx-app
          image: akhilreddyv371/my-nginx-app:latest  # Replace with your image
          ports:
            - containerPort: 80
